SRCS += $(PLATFORM_DIR)/serial.c \
        $(PLATFORM_DIR)/gdt.c \
        $(PLATFORM_DIR)/idt.c \
	$(PLATFORM_DIR)/isr.c \
        $(PLATFORM_DIR)/pic.c \
        $(PLATFORM_DIR)/platform.c \
	$(PLATFORM_DIR)/asm.S
